### ISSUE TITLE
Supporting react-router v4 and higher

### ISSUE THREAD

**Issue by VinhVu0412** [MrLeebo/redux-breadcrumb-trail#10]
Do you have any plan to improve this package?

**Comment by MrLeebo** [comment]
Hi @VinhVu0412,

I haven't found it very helpful to keep breadcrumb information in Redux anymore, and the changes to the way routes are defined in react-router past v3 really make you re-evaluate how to keep Route information in your App. 

The newer approach I'm using relies on React Hooks/Context instead of Redux and you render two components:

```jsx
function Layout({ children }) {
  return (
    <Breadcrumbs>
      {({breadcrumbs}) => (
        <>
          <div className="breadcrumbs">
            {breadcrumbs.map((crumb, index) => (
              <Link key={index} to={crumb.to}>{crumb.children}</Link>
            ))}
          </div>

          {children}
        </>
      )}
    </Breadcrumbs>
  )
}
```

The first is the Breadcrumbs component which renders the breadcrumb links and provides Context to your app.

```jsx
function AboutPage() {
  return (
    <>
      <Breadcrumb title="About" />

      <h1>About Page</h1>
      <p>About page stuff...</p>
    </>
  )
}
```

The second is the component you declare inside of your Pages to push new breadcrumbs to the list. Since the Breadcrumb is declared inside the Page instead of beside it, you can more easily include async/dynamic data inside your Breadcrumb text.

It's a pretty big change from what this library was originally trying to do. I don't have a full repo/npm package for this approach, but this Demo should have everything you need.

https://codesandbox.io/s/breadcrumb-react-router-dom-demo-smp32

- The react-router-dom router is declared in app.js
- person.js has an example of a Breadcrumb which changes the title dynamically
- The breadcrumb links are rendered in layout.js

Take a look at that and let me know if that suits your needs 😉.

**Comment by MrLeebo** [comment]
Closing... assuming that helped.
