### ISSUE TITLE
Optionally treat parametrised routes as one page

### ISSUE THREAD

**Issue by asliwinski** [MrLeebo/redux-breadcrumb-trail#4]
> If you visit the same route but the params are different (e.g. <Route path="/product/:id" /> for two different IDs) that would be two different pages

Can this behaviour be different, i.e. treat the parametrized routes as one page? I'd like to use your package to cover the use case of unnested routes: https://github.com/svenanders/react-breadcrumbs/issues/42
Having parametrized routes treated as different pages would be a downside in this case.

**Comment by MrLeebo** [comment]
@asliwinski Hi, good question! If you are willing to change your page layout slightly, you can accomplish this with the current version of **redux-breadcrumb-trail** by either

1) Using query string parameters instead of URL parameters for your ID (`/page?id=1` instead of `/page/1`), or
2) Add a parent route on top of your parameterized route and use the `useParentBreadcrumb` prop. Something like:

```jsx
<Route path="page" component={PageLayout} breadcrumb={PageBreadcrumb}>
  <Route path=":id" component={PageDetail} useParentBreadcrumb />
</Route>
```

But if neither of those solutions work then it would be easy to make a code change to add a new option, changing the matching behavior, like: 
```jsx
<Route path="page/:id" component={Page} breadcrumb={PageBreadcrumb} ignoreParams />
```

**Comment by MrLeebo** [comment]
@asliwinski I am going to close this because I released https://github.com/MrLeebo/redux-breadcrumb-trail/releases/tag/v0.3.0 which includes the `ignoreParams` option as described in the previous comment. Feel free to re-open if that doesn't work for you.
